### ISSUE TITLE
Idea on how to reuse pre-existing methods 

### ISSUE THREAD

**Issue by TrevorSmith1275** [apatton1247/Munchkin#2]
I want to reuse the monster Bias method for items that are class specific. 
-more detail in the item class milestone description. True/False

I also want to standardize the use of bribe (originally exclusive to the floating nose) for pit bull and other monsters that will react if you give them something. Like the walking hand or whatever it is that like the rat on a stick.

**Comment by apatton1247** [comment]
Project abandoned, no issue now.
